apiVersion: v1
kind: Service
metadata:
  name: interview-app
  namespace: infrastructure-interview
spec:
  type: NodePort

  selector:
    app: interview-app

  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080