apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: infrastructure-interview
spec:
  serviceName: mariadb
  replicas: 1

  selector:
    matchLabels:
      app: mariadb

  template:
    metadata:
      labels:
        app: mariadb
    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: mariadb
          image: mariadb:11.4.13
          imagePullPolicy: IfNotPresent

          ports:
            - name: mysql
              containerPort: 3306

          env:
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TYPEORM_DATABASE

            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: username

            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password

            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: root-password

          readinessProbe:
            tcpSocket:
              port: mysql
            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi